name: Deployment Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main
    types: [opened, synchronize]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{github.token}}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm run test 
      - name: E2E test
        uses: cypress-io/github-action@v2
        with: 
          command: npm run test:e2e
          start: npm run start test 
          wait-on: http://localhost:5007
      - name: Heroku Deployment
        if: ${{github.event.event_name == 'push'}} 
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.API_KEY}}
          heroku_app_name: ${{secrets.APP_NAME}} #Must be unique in Heroku
          heroku_email: ${{secrets.EMAIL}}
          healthcheck: "https://${{secrets.APP_NAME}}.herokuapp.com/health"
          rollbackonhealthcheckfailed: true 